"""add token cols to fitbit_accounts

Revision ID: 3b0beea187e4
Revises: 
Create Date: 2025-10-27 09:49:43.804478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b0beea187e4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weights_measured_at_utc'), table_name='weights')
    op.drop_index(op.f('ix_weights_provider'), table_name='weights')
    op.drop_index(op.f('ix_weights_provider_measure_id'), table_name='weights')
    op.drop_index(op.f('ix_weights_user_id'), table_name='weights')
    op.drop_table('weights')
    op.drop_table('fitbit_accounts')
    op.drop_index(op.f('ix_heart_rate_daily_date_local'), table_name='heart_rate_daily')
    op.drop_index(op.f('ix_heart_rate_daily_provider'), table_name='heart_rate_daily')
    op.drop_index(op.f('ix_heart_rate_daily_user_id'), table_name='heart_rate_daily')
    op.drop_table('heart_rate_daily')
    op.drop_index(op.f('ix_distance_daily_date_local'), table_name='distance_daily')
    op.drop_index(op.f('ix_distance_daily_provider'), table_name='distance_daily')
    op.drop_index(op.f('ix_distance_daily_user_id'), table_name='distance_daily')
    op.drop_table('distance_daily')
    op.drop_index(op.f('ix_metrics_intraday_date_local'), table_name='metrics_intraday')
    op.drop_index(op.f('ix_metrics_intraday_metric'), table_name='metrics_intraday')
    op.drop_index(op.f('ix_metrics_intraday_provider'), table_name='metrics_intraday')
    op.drop_index(op.f('ix_metrics_intraday_ts_utc'), table_name='metrics_intraday')
    op.drop_index(op.f('ix_metrics_intraday_user_id'), table_name='metrics_intraday')
    op.drop_table('metrics_intraday')
    op.drop_index(op.f('ix_spo2_readings_measured_at_utc'), table_name='spo2_readings')
    op.drop_index(op.f('ix_spo2_readings_provider'), table_name='spo2_readings')
    op.drop_index(op.f('ix_spo2_readings_reading_id'), table_name='spo2_readings')
    op.drop_index(op.f('ix_spo2_readings_type'), table_name='spo2_readings')
    op.drop_index(op.f('ix_spo2_readings_user_id'), table_name='spo2_readings')
    op.drop_table('spo2_readings')
    op.drop_index(op.f('ix_metrics_daily_date_local'), table_name='metrics_daily')
    op.drop_index(op.f('ix_metrics_daily_metric'), table_name='metrics_daily')
    op.drop_index(op.f('ix_metrics_daily_provider'), table_name='metrics_daily')
    op.drop_index(op.f('ix_metrics_daily_user_id'), table_name='metrics_daily')
    op.drop_table('metrics_daily')
    op.drop_index(op.f('ix_steps_daily_date_local'), table_name='steps_daily')
    op.drop_index(op.f('ix_steps_daily_provider'), table_name='steps_daily')
    op.drop_index(op.f('ix_steps_daily_user_id'), table_name='steps_daily')
    op.drop_table('steps_daily')
    op.drop_index(op.f('ix_temperature_readings_measured_at_utc'), table_name='temperature_readings')
    op.drop_index(op.f('ix_temperature_readings_provider'), table_name='temperature_readings')
    op.drop_index(op.f('ix_temperature_readings_user_id'), table_name='temperature_readings')
    op.drop_table('temperature_readings')
    op.drop_index(op.f('ix_daily_snapshot_date_local'), table_name='daily_snapshot')
    op.drop_index(op.f('ix_daily_snapshot_provider'), table_name='daily_snapshot')
    op.drop_index(op.f('ix_daily_snapshot_user_id'), table_name='daily_snapshot')
    op.drop_table('daily_snapshot')
    op.drop_table('users')
    op.drop_index(op.f('ix_heart_rate_intraday_date_local'), table_name='heart_rate_intraday')
    op.drop_index(op.f('ix_heart_rate_intraday_provider'), table_name='heart_rate_intraday')
    op.drop_index(op.f('ix_heart_rate_intraday_user_id'), table_name='heart_rate_intraday')
    op.drop_table('heart_rate_intraday')
    op.drop_index(op.f('ix_steps_intraday_date_local'), table_name='steps_intraday')
    op.drop_index(op.f('ix_steps_intraday_provider'), table_name='steps_intraday')
    op.drop_index(op.f('ix_steps_intraday_user_id'), table_name='steps_intraday')
    op.drop_table('steps_intraday')
    op.drop_index(op.f('ix_ecg_records_end_at_utc'), table_name='ecg_records')
    op.drop_index(op.f('ix_ecg_records_provider'), table_name='ecg_records')
    op.drop_index(op.f('ix_ecg_records_record_id'), table_name='ecg_records')
    op.drop_index(op.f('ix_ecg_records_start_at_utc'), table_name='ecg_records')
    op.drop_index(op.f('ix_ecg_records_user_id'), table_name='ecg_records')
    op.drop_table('ecg_records')
    op.drop_table('withings_accounts')
    op.drop_index(op.f('ix_distance_intraday_date_local'), table_name='distance_intraday')
    op.drop_index(op.f('ix_distance_intraday_provider'), table_name='distance_intraday')
    op.drop_index(op.f('ix_distance_intraday_user_id'), table_name='distance_intraday')
    op.drop_table('distance_intraday')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('distance_intraday',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('date_local', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('start_at_utc', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('end_at_utc', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('resolution', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('samples_json', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('distance_intraday_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('distance_intraday_pkey')),
    sa.UniqueConstraint('user_id', 'provider', 'date_local', 'resolution', name=op.f('uq_distance_intraday_user_provider_date_res'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_distance_intraday_user_id'), 'distance_intraday', ['user_id'], unique=False)
    op.create_index(op.f('ix_distance_intraday_provider'), 'distance_intraday', ['provider'], unique=False)
    op.create_index(op.f('ix_distance_intraday_date_local'), 'distance_intraday', ['date_local'], unique=False)
    op.create_table('withings_accounts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('withings_user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('timezone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('access_token', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('refresh_token', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('scope', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('token_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('withings_accounts_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('withings_accounts_pkey')),
    sa.UniqueConstraint('user_id', 'withings_user_id', name=op.f('uq_withings_user_per_app_user'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('ecg_records',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('record_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('start_at_utc', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('end_at_utc', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('hr_bpm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('classification', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('duration_s', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('file_ref', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('ecg_records_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('ecg_records_pkey')),
    sa.UniqueConstraint('user_id', 'provider', 'record_id', name=op.f('uq_ecg_user_provider_rid'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_ecg_records_user_id'), 'ecg_records', ['user_id'], unique=False)
    op.create_index(op.f('ix_ecg_records_start_at_utc'), 'ecg_records', ['start_at_utc'], unique=False)
    op.create_index(op.f('ix_ecg_records_record_id'), 'ecg_records', ['record_id'], unique=False)
    op.create_index(op.f('ix_ecg_records_provider'), 'ecg_records', ['provider'], unique=False)
    op.create_index(op.f('ix_ecg_records_end_at_utc'), 'ecg_records', ['end_at_utc'], unique=False)
    op.create_table('steps_intraday',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('date_local', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('start_at_utc', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('end_at_utc', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('resolution', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('samples_json', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('steps_intraday_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('steps_intraday_pkey')),
    sa.UniqueConstraint('user_id', 'provider', 'date_local', 'resolution', name=op.f('uq_steps_intraday_user_provider_date_res'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_steps_intraday_user_id'), 'steps_intraday', ['user_id'], unique=False)
    op.create_index(op.f('ix_steps_intraday_provider'), 'steps_intraday', ['provider'], unique=False)
    op.create_index(op.f('ix_steps_intraday_date_local'), 'steps_intraday', ['date_local'], unique=False)
    op.create_table('heart_rate_intraday',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('date_local', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('start_at_utc', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('end_at_utc', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('resolution', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('samples_json', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('heart_rate_intraday_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('heart_rate_intraday_pkey')),
    sa.UniqueConstraint('user_id', 'provider', 'date_local', 'resolution', name=op.f('uq_hr_intraday_user_provider_date_res'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_heart_rate_intraday_user_id'), 'heart_rate_intraday', ['user_id'], unique=False)
    op.create_index(op.f('ix_heart_rate_intraday_provider'), 'heart_rate_intraday', ['provider'], unique=False)
    op.create_index(op.f('ix_heart_rate_intraday_date_local'), 'heart_rate_intraday', ['date_local'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('auth_user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('display_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('auth_user_id', name='users_auth_user_id_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('daily_snapshot',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('date_local', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('steps', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('distance_km', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('calories', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('avg_hr', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('hr_min', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('hr_max', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sleep_total_min', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('weight_kg_latest', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('spo2_avg_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('temp_body_c', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('temp_skin_c', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ecg_latest_bpm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ecg_latest_time_utc', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('tz', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('source_updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('daily_snapshot_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('daily_snapshot_pkey')),
    sa.UniqueConstraint('user_id', 'date_local', 'provider', name=op.f('uq_daily_snapshot_user_date_provider'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_daily_snapshot_user_id'), 'daily_snapshot', ['user_id'], unique=False)
    op.create_index(op.f('ix_daily_snapshot_provider'), 'daily_snapshot', ['provider'], unique=False)
    op.create_index(op.f('ix_daily_snapshot_date_local'), 'daily_snapshot', ['date_local'], unique=False)
    op.create_table('temperature_readings',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('measured_at_utc', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('body_c', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('skin_c', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('delta_c', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('temperature_readings_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('temperature_readings_pkey')),
    sa.UniqueConstraint('user_id', 'provider', 'measured_at_utc', name=op.f('uq_temp_user_provider_ts'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_temperature_readings_user_id'), 'temperature_readings', ['user_id'], unique=False)
    op.create_index(op.f('ix_temperature_readings_provider'), 'temperature_readings', ['provider'], unique=False)
    op.create_index(op.f('ix_temperature_readings_measured_at_utc'), 'temperature_readings', ['measured_at_utc'], unique=False)
    op.create_table('steps_daily',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('date_local', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('steps', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('active_min', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('calories', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('steps_daily_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('steps_daily_pkey')),
    sa.UniqueConstraint('user_id', 'provider', 'date_local', name=op.f('uq_steps_daily_user_provider_date'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_steps_daily_user_id'), 'steps_daily', ['user_id'], unique=False)
    op.create_index(op.f('ix_steps_daily_provider'), 'steps_daily', ['provider'], unique=False)
    op.create_index(op.f('ix_steps_daily_date_local'), 'steps_daily', ['date_local'], unique=False)
    op.create_table('metrics_daily',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('metric', sa.VARCHAR(length=48), autoincrement=False, nullable=False),
    sa.Column('date_local', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('unit', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('tz', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('source_updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('metrics_daily_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('metrics_daily_pkey')),
    sa.UniqueConstraint('user_id', 'provider', 'metric', 'date_local', name=op.f('uq_metric_daily_user_provider_metric_date'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_metrics_daily_user_id'), 'metrics_daily', ['user_id'], unique=False)
    op.create_index(op.f('ix_metrics_daily_provider'), 'metrics_daily', ['provider'], unique=False)
    op.create_index(op.f('ix_metrics_daily_metric'), 'metrics_daily', ['metric'], unique=False)
    op.create_index(op.f('ix_metrics_daily_date_local'), 'metrics_daily', ['date_local'], unique=False)
    op.create_table('spo2_readings',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('measured_at_utc', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('avg_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('min_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=16), autoincrement=False, nullable=True),
    sa.Column('reading_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('spo2_readings_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('spo2_readings_pkey')),
    sa.UniqueConstraint('user_id', 'provider', 'reading_id', name=op.f('uq_spo2_user_provider_rid'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_spo2_readings_user_id'), 'spo2_readings', ['user_id'], unique=False)
    op.create_index(op.f('ix_spo2_readings_type'), 'spo2_readings', ['type'], unique=False)
    op.create_index(op.f('ix_spo2_readings_reading_id'), 'spo2_readings', ['reading_id'], unique=False)
    op.create_index(op.f('ix_spo2_readings_provider'), 'spo2_readings', ['provider'], unique=False)
    op.create_index(op.f('ix_spo2_readings_measured_at_utc'), 'spo2_readings', ['measured_at_utc'], unique=False)
    op.create_table('metrics_intraday',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('metric', sa.VARCHAR(length=48), autoincrement=False, nullable=False),
    sa.Column('ts_utc', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('date_local', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('unit', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('tz', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('metrics_intraday_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('metrics_intraday_pkey')),
    sa.UniqueConstraint('user_id', 'provider', 'metric', 'ts_utc', name=op.f('uq_metric_intraday_user_provider_metric_ts'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_metrics_intraday_user_id'), 'metrics_intraday', ['user_id'], unique=False)
    op.create_index(op.f('ix_metrics_intraday_ts_utc'), 'metrics_intraday', ['ts_utc'], unique=False)
    op.create_index(op.f('ix_metrics_intraday_provider'), 'metrics_intraday', ['provider'], unique=False)
    op.create_index(op.f('ix_metrics_intraday_metric'), 'metrics_intraday', ['metric'], unique=False)
    op.create_index(op.f('ix_metrics_intraday_date_local'), 'metrics_intraday', ['date_local'], unique=False)
    op.create_table('distance_daily',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('date_local', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('distance_km', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('distance_daily_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('distance_daily_pkey')),
    sa.UniqueConstraint('user_id', 'provider', 'date_local', name=op.f('uq_distance_daily_user_provider_date'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_distance_daily_user_id'), 'distance_daily', ['user_id'], unique=False)
    op.create_index(op.f('ix_distance_daily_provider'), 'distance_daily', ['provider'], unique=False)
    op.create_index(op.f('ix_distance_daily_date_local'), 'distance_daily', ['date_local'], unique=False)
    op.create_table('heart_rate_daily',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('date_local', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('avg_bpm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('min_bpm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('max_bpm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sample_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('heart_rate_daily_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('heart_rate_daily_pkey')),
    sa.UniqueConstraint('user_id', 'provider', 'date_local', name=op.f('uq_hr_daily_user_provider_date'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_heart_rate_daily_user_id'), 'heart_rate_daily', ['user_id'], unique=False)
    op.create_index(op.f('ix_heart_rate_daily_provider'), 'heart_rate_daily', ['provider'], unique=False)
    op.create_index(op.f('ix_heart_rate_daily_date_local'), 'heart_rate_daily', ['date_local'], unique=False)
    op.create_table('fitbit_accounts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('fitbit_user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('timezone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('refresh_token', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('scope', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('token_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fitbit_accounts_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('fitbit_accounts_pkey')),
    sa.UniqueConstraint('user_id', 'fitbit_user_id', name=op.f('uq_fitbit_user_per_app_user'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('weights',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('measured_at_utc', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('weight_kg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('fat_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('provider_measure_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('device', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('tz_offset_min', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('weights_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('weights_pkey')),
    sa.UniqueConstraint('user_id', 'provider', 'provider_measure_id', name=op.f('uq_weight_provider_id'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_weights_user_id'), 'weights', ['user_id'], unique=False)
    op.create_index(op.f('ix_weights_provider_measure_id'), 'weights', ['provider_measure_id'], unique=False)
    op.create_index(op.f('ix_weights_provider'), 'weights', ['provider'], unique=False)
    op.create_index(op.f('ix_weights_measured_at_utc'), 'weights', ['measured_at_utc'], unique=False)
    # ### end Alembic commands ###
