import os
from dotenv import load_dotenv

load_dotenv()

WITHINGS_CLIENT_ID = os.getenv("WITHINGS_CLIENT_ID")
WITHINGS_REDIRECT_URI = os.getenv("WITHINGS_REDIRECT_URI")
WITHINGS_CLIENT_SECRET = os.getenv("WITHINGS_CLIENT_SECRET")

FITBIT_CLIENT_ID = os.getenv("FITBIT_CLIENT_ID")
FITBIT_REDIRECT_URI = os.getenv("FITBIT_REDIRECT_URI")
FITBIT_CLIENT_SECRET = os.getenv("FITBIT_CLIENT_SECRET")

